<h1>Dados do Formulário</h1>
<?php

$morador = $_POST['morador'];
$nome = $_POST ['nome'];
$data = $_POST['nascimento'];
$sexo = $_POST ['txtsexo'];
$escolaridade = $_POST['escolaridade'];
$email = $_POST ['email'];
$bairro = $_POST ['bairro'];
$idade = $_POST ['idade'];
$nsidade = $_POST ['nsidade'];
$autodec = $_POST ['autodec'];
$rendafam = $_POST ['rendafam'];
$nummembros = $_POST ['nummembros'];
$quest1 = $_POST ['txtq1'];
$quest2= $_POST ['txtq2'];
$quest3 = $_POST ['txtq3'];
$quest4 = $_POST ['txtq4'];
$quest5 = $_POST ['txtq5'];
$quest6 = $_POST ['txtq6'];
$quest7 = $_POST ['txtq7'];
$quest8 = $_POST ['txtq8'];
$c1a = $_POST ['c1a'];
$c1b = $_POST ['c1b'];
$c1c = $_POST ['c1c'];
$c2 = $_POST ['c2']; 
$c3a = $_POST ['c3a']; 
$c3b = $_POST ['c3b']; 
$c4 = $_POST ['c4']; 
$c5a = $_POST ['c5a'];
$c5b = $_POST ['c5b']; 
$c6 = $_POST ['c6']; 
$c7a = $_POST ['c7a']; 
$c7b = $_POST ['c7b']; 
$c7c = $_POST ['c7c']; 
$c8a = $_POST ['c8a']; 
$c8b = $_POST ['c8b']; 
$c9 = $_POST ['c9']; 
$c10 = $_POST ['c10']; 


echo "Morador $morador";
echo "Nome: $nome <br>";
echo "Data de nascimento: $data <br>";
echo "Sexo: $sexo <br>" ;
echo "Escolaridade: $escolaridade <br>" ;
echo "Telefone: $telefone <br>";
echo "Email: $email <br>";
echo "Bairro: $bairro <br>";
echo "Idade: $idade <br>";
echo "Não sabe a idade: $nsidade <br>";
echo "Auto declaração: $autodec <br>";
echo "Renda familiar: $rendafam <br>";
echo "número de membros família: $nummembros <br>";
echo "Você acha que entende tudo... $quest1 <br>";
echo "Você se sente seguro... $quest2 <br>";
echo "Qual é o seu grau de dificuldade ao ler um texto? $quest3 <br>";
echo "Costuma pedir ajuda... $quest4 <br>";
echo "Algum membro de sua família... $quest5 <br>";
echo "Alguém da sua família já... $quest6 <br>";
echo "Você possui o hábito de ler... $quest7 <br>";
echo "Você possui certa dificuldade... $quest8 <br>";
echo "Cartão 1a: $c1a <br>";
echo "Cartão 1b: $c1b <br>";
echo "Cartão 1c: $c1c <br>";
echo "Cartão 2: $c2 <br>";
echo "Cartão 3a: $c3a <br>";
echo "Cartão 3b: $c3b <br>";
echo "Cartão 4: $c4 <br>";
echo "Cartão 5a: $c5a <br>";
echo "Cartão 5b: $c5b <br>";
echo "Cartão 6: $c6 <br>";
echo "Cartão 7a: $c7a <br>";
echo "Cartão 7b: $c7b <br>";
echo "Cartão 7c: $c7c <br>";
echo "Cartão 8a: $c8a <br>";
echo "Cartão 8b: $c8b <br>";
echo "Cartão 9: $c9 <br>";
echo "Cartão 10: $c10 <br>";

?>
